import AddComment from "./AddComment"
import Comments from "./Comments"
import Layout from "./Layout"
import MobileTabs from "./MobileTabs"
import QuestionForm from "./QuestionForm"
import Questions from "./Questions"
import Reviews from "./Reviews"
import Slider from "./Slider"
import Tabs from "./Tabs"

export { AddComment }
export { Comments }
export { Layout }
export { MobileTabs }
export { QuestionForm }
export { Questions }
export { Reviews }
export { Slider }
export { Tabs }
