import Add from "./Add"
import Bars from "./Bars"
import Calendar from "./Calendar"
import Category from "./Category"
import Chat from "./Chat"
import Check from "./Check"
import CheckBook from "./CheckBook"
import Checked from "./Checked"
import Clipboard from "./Clipboard"
import Close from "./Close"
import CloseMenu from "./CloseMenu"
import Document from "./Document"
import EighteenWheeler from "./EighteenWheeler"
import Email from "./Email"
import Employee from "./Employee"
import Eye from "./Eye"
import FilterAlt from "./FilterAlt"
import Language from "./Language"
import Left from "./Left"
import Loading from "./Loading"
import Location from "./Location"
import LocationThick from "./LocationThick"
import Magnifying from "./Magnifying"
import OldPhone from "./OldPhone"
import OpenMenu from "./OpenMenu"
import Person from "./Person"
import Phone from "./Phone"
import PinDrop from "./PinDrop"
import PriorityHigh from "./PriorityHigh"
import Question from "./Question"
import Remove from "./Remove"
import Right from "./Right"
import Road from "./Road"
import RotateLeft from "./RotateLeft"
import Search from "./Search"
import Shopping from "./Shopping"
import ShoppingCart from "./ShoppingCart"
import Star from "./Star"
import Tag from "./Tag"
import Trash from "./Trash"
import Tune from "./Tune"
import User from "./User"
import Whatsapp from "./Whatsapp"
import ZoomOut from "./ZoomOut"

export { Add }
export { Bars }
export { Calendar }
export { Category }
export { Chat }
export { Check }
export { CheckBook }
export { Checked }
export { Clipboard }
export { Close }
export { CloseMenu }
export { Document }
export { EighteenWheeler }
export { Email }
export { Employee }
export { Eye }
export { FilterAlt }
export { Language }
export { Left }
export { Loading }
export { Location }
export { LocationThick }
export { Magnifying }
export { OldPhone }
export { OpenMenu }
export { Person }
export { Phone }
export { PinDrop }
export { PriorityHigh }
export { Question }
export { Remove }
export { Right }
export { Road }
export { RotateLeft }
export { Search }
export { Shopping }
export { ShoppingCart }
export { Star }
export { Tag }
export { Trash }
export { Tune }
export { User }
export { Whatsapp }
export { ZoomOut }
