import CtaSection from "./CtaSection"
import Hero from "./Hero"
import HorizontalMenu from "./HorizontalMenu"
import Industries from "./Industries"
import Posts from "./Posts"
import Solutions from "./Solutions"
import SpecialServicesCard from "./SpecialServicesCard"
import Stats from "./Stats"
import TrucksSearchBox from "./TrucksSearchBox"

export { CtaSection }
export { Hero }
export { HorizontalMenu }
export { Industries }
export { Posts }
export { Solutions }
export { SpecialServicesCard }
export { Stats }
export { TrucksSearchBox }
